name: vagrant-ubuntu-up

on: [push]

jobs:
  first:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: First job      
          - name: First another job       

    env:
      files_artefact: Files (${{ matrix.name }})

    steps:

    - name: Create files
      run: |
        mkdir -p build/dir1/dir2/dir3
        echo "000" > build/file0
        echo "111" > build/dir1/file1
        echo "222" > build/dir1/dir2/file2
        echo "333" > build/dir1/dir2/dir3/file3
        mkdir -p dir
        echo "abracadabra" > dir/abracadabra.txt
        echo "text" > dir/text.txt

    - name: Display files in working directory
      run: ls -Rhl

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.files_artefact }}
        path: |
          build/file0
          build/dir1/file1
          build/dir1/dir2/file2
          build/dir1/dir2/dir3/file3
        retention-days: 1

    - name: Upload folder
      uses: actions/upload-artifact@v3
      with:
        name: Folder
        path: dir
        retention-days: 1

  second:
    runs-on: macos-latest
    needs: [first]

    defaults:
      run:
        working-directory: files

    steps:

    - name: Checkout files
      uses: Bhacaz/checkout-files@v2
      with:
        files: files

    - name: Download files
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.first.env.files_artefact }}
        path: files

    - name: Download folder
      uses: actions/download-artifact@v3
      with:
        name: Folder
        path: files

    - name: Select first file with extention
      run: |
        textfiles=( *.txt )
        echo "${textfiles[0]}"

    - name: Display files in working directory
      run: ls -Rhl

    - name: Delete unused artifact
      uses: geekyeggo/delete-artifact@v2
      with:
          name: Folder
