name: vagrant-ubuntu-up

on: [push]

env:
  package_path: ${{ github.workspace }}/build/_packages

jobs:
  first:
    runs-on: ubuntu-latest

    steps:

    - name: Find package and run vagrant
      run: |
        mkdir simulator
        mkdir -p build/_packages
        echo "smth" > ${{ env.package_path }}/smth_0.4.0_amd64.deb

    - name: Find package and run vagrant
      working-directory: simulator
      run: |
        debfiles=( ../build/_packages/*.deb )
        echo "Package is ${debfiles[0]}"
